# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=255)),
                ('age', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('region', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=255)),
            ],
        ),
    ]
