# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockscreen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image_url',
            field=models.CharField(max_length=1000),
        ),
    ]
